export const dashboard = <i className="fa-solid fa-chart-line  w-10 h-10 custom-icon-size"></i>
export const transactions = <i className="fa-solid fa-credit-card  w-10 h-10 custom-icon-size"></i>
export const categories = <i className="fa-solid fa-tags  w-10 h-10 custom-icon-size"></i>
export const accounts = <i className="fa-solid fa-wallet  w-10 h-10 custom-icon-size"></i>
export const settings = <i className="fa-solid fa-cog  w-10 h-10 custom-icon-size"></i>
export const logout = <i className="fa-solid fa-sign-out  w-10 h-10 custom-icon-size"></i>
export const trend = <i className="fa-solid fa-money-bill-trend-up  w-10 h-10 custom-icon-size"></i>
export const expenses = <i className="fa-solid fa-money-bill-transfer  w-10 h-10 custom-icon-size"></i>
export const money = <i className="fa-solid fa-money-bill  w-10 h-10 custom-icon-size"></i>
export const freelance = <i className="fa-solid fa-earth-americas  w-10 h-10 custom-icon-size"></i>
export const stocks = <i className="fa-solid fa-arrow-trend-up  w-10 h-10 custom-icon-size"></i>
export const bitcoin = <i className="fa-brands fa-bitcoin  w-10 h-10 custom-icon-size"></i>
export const piggy = <i className="fa-solid fa-piggy-bank  w-10 h-10 custom-icon-size"></i>
export const yt = <i className="fa-brands fa-youtube  w-10 h-10 custom-icon-size"></i>
export const card = <i className="fa-brands fa-cc-visa  w-10 h-10 custom-icon-size"></i>
export const users = <i className="fa-solid fa-users-between-lines  w-10 h-10 custom-icon-size"></i>
export const dollar = <i className="fa-solid fa-dollar-sign  w-10 h-10 custom-icon-size"></i>
export const calender = <i className="fa-solid fa-calendar  w-10 h-10 custom-icon-size"></i>
export const comment = <i className="fa-solid fa-comment  w-10 h-10 custom-icon-size"></i>
export const plus = <i className="fa-solid fa-plus  w-10 h-10 custom-icon-size"></i>
export const trash = <i className="fa-solid fa-trash  w-10 h-10 custom-icon-size"></i>
export const signout = <i className="fa-solid fa-right-from-bracket  w-10 h-10 custom-icon-size"></i>
export const takeaway = <i className="fa-solid fa-utensils  w-10 h-10 custom-icon-size"></i>
export const clothing = <i className="fa-solid fa-shirt  w-10 h-10 custom-icon-size"></i>
export const book = <i className="fa-solid fa-book-open  w-10 h-10 custom-icon-size"></i>
export const food = <i className="fa-solid fa-bowl-food  w-10 h-10 custom-icon-size"></i>
export const medical = <i className="fa-solid fa-briefcase-medical  w-10 h-10 custom-icon-size"></i>
export const tv = <i className="fa-solid fa-tv  w-10 h-10 custom-icon-size"></i>
export const circle = <i className="fa-solid fa-circle-dot  w-10 h-10 custom-icon-size"></i>
